language: python
python:
- 3.6
services:
- postgresql
addons:
  postgresql: '9.4'
before_install:
- openssl aes-256-cbc -K $encrypted_c310a5f9fe5d_key -iv $encrypted_c310a5f9fe5d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- tar xvf front.tar
install:
- pip install -r requirements.txt
branches:
  only:
  - master
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- cd app
- "./manage.py test"
- cd ..
- git add -A
before_deploy:
- zip -r archive.zip .
deploy:
  provider: elasticbeanstalk
  zip_file: archive.zip
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: ap-northeast-2
  app: baeminchan-django
  env: baeminchan-django-dev
  bucket_name: baeminchan-bucket
  skip_cleanup: true
  on:
    branch: master
